# West US 3 Region Configuration

azure_region_config:
  name: "West US 3"
  code: "wus3"
  full_name: "westus3"
  timezone: "America/Los_Angeles"
  maintenance_window: "02:00-04:00 PST"

azure_infrastructure:
  subscription_id: "{{ vault_wus3_subscription_id }}"
  resource_group: "rg-prod-wus3"
  vnet_name: "vnet-prod-wus3"
  key_vault: "kv-prod-wus3"
  
azure_devops:
  pipeline_id: "{{ vault_wus3_pipeline_id }}"
  environment: "wus3-production"
  
network_config:
  vnet_cidr: "10.3.0.0/16"
  subnets:
    web: "10.3.1.0/24"
    db: "10.3.2.0/24"
    monitoring: "10.3.3.0/24"
    
security_groups:
  web_nsg: "nsg-wus3-web"
  db_nsg: "nsg-wus3-db"
  monitoring_nsg: "nsg-wus3-monitoring"